name: Ansible CI

on: [push]

jobs:

  ansible_lint:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      with:
        path: 'input'

    - uses: actions/checkout@v2
      with:
        repository: 'AnsibleCI/MyAnsibleCI'
        path: 'output' 

    - name: Docker login
      run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}    

    - name: Pull Docker image
      run: docker pull "docker.pkg.github.com/ansibleci/docker-img-ansible/ansibleci:0.0.2"

    - name: Run image
      run: docker run --rm -t --name ansible_lint -v $GITHUB_WORKSPACE/input:/input -v $GITHUB_WORKSPACE/output:/output docker.pkg.github.com/ansibleci/docker-img-ansible/ansibleci:0.0.2 ansible-playbook ansible-lint.yml
      
    - name: print results
      run: ls -lR $GITHUB_WORKSPACE

    - name: git commit and push to 'AnsibleCI/MyAnsibleCI'
      run: |
        cd $GITHUB_WORKSPACE/output
        git config --local user.email "ansibleci@github.com"
        git config --local user.name "AnsibleCI Github Action"
        git add -A
        git commit -m "AnsibleCI update for commit '${{github.sha}}' on '${{github.repository}}'"
        git push https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/AnsibleCI/MyAnsibleCI.git
      env:
          GITHUB_TOKEN: ${{secrets.ANSIBLECI_RW_TOKEN}}  
